version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "5002:5002"
    env_file:
      - ./backend/.env
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - ./backend:/app
      - /app/venv

  frontend:
    build: ./frontend
    ports:
      - "8081:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - ./frontend:/app
      - /app/node_modules

networks:
  app-network:
    driver: bridge